### ISSUE TITLE
Error if image is not in the bucket root

### ISSUE THREAD

**Issue by 7haveeen** [HoraceShmorace/Image-Flex#1]
original URL:  distribution/uploads/test.jpeg?w=200
Error while getting source image object "/uploadstest.jpeg": NoSuchKey: The specified key does not exist.

If the image is in the subfolder i get the following error how to fix it.

**Comment by HoraceShmorace** [comment]
Thanks for reporting this. I fixed a small bug in commit 9edff8cbf58eec6bfd97c4cc726be8fe0dbd25a7.
