### ISSUE TITLE
VipsJpeg: Insufficient memory

### ISSUE THREAD

**Issue by leomeneguzzi** [HoraceShmorace/Image-Flex#12]
Hi, I'm facing the following error with some images that are a little bit heavy, around 5MB. Did you face this error too? Or do you know a workaround for this? Unfortunately, the memory limit to lambda@edge is 256MB :(

```json
{
    "errorType": "Error",
    "errorMessage": "VipsJpeg: Insufficient memory (case 4)\n",
    "stack": [
        "Error: VipsJpeg: Insufficient memory (case 4)",
        ""
    ]
}
```

**Comment by leomeneguzzi** [comment]
Actually, I'm looking here, and to the `origin-response` lambda@edge, the memory limit seems to be the same to the lambda functions 🤔

**Comment by leomeneguzzi** [comment]
I solve the problem increasing the memory to 1024MB. But to some images I'm getting timeout... And I think that it's using a huge amount of memory considering that each lambda do just one resize.

Do you have some tip to improve it? I tried do the download of the image, the resize and the write process using streaming, but I think that lambda don't support give the response to client as a stream, just as json... Then I don't have another choice than process and get the Base64.

Another possibility that I think is use Golang with govips, but probably will have almost the same performance and memory usage result because the program is simple, the huge process is made by libvips, that will be the same anyway. But I didn't the tests, it's just my feeling.

Anyway, anyway has some tip to performance or memory improvement? Or some crazy idea to improve it?

Anyway, thanks very much for the repository, was great to me, save me probably more - than 5 days of hardworking

**Comment by HoraceShmorace** [comment]
Hmm. I've resized some fairly large JPEGs with this. I'll do some performance testing (probably this weekend) and get back to you.

**Comment by HoraceShmorace** [comment]
I finally got around to this. I was able to resize up to 100mb jpegs without any real issues (it's obviously slower as the file sizes grow, but nothing unexpected). I haven't tested any higher than that yet.

**Comment by HoraceShmorace** [comment]
These links seem to provide some clarity:
https://github.com/lovell/sharp/issues/177#issuecomment-451552383
https://github.com/lovell/sharp/issues/955
