### ISSUE TITLE
Size Issue

### ISSUE THREAD

**Issue by 7haveeen** [HoraceShmorace/Image-Flex#2]
Hie the solution is working great but rather I noted a huge growth in my page size after inspecting thoroughly I found out that if I upload a jpeg with 1200x800 size 88kb then try to resize it to ?w=500 the size actually grows from 88kb to 265kb when it is supposed to have gone down. I tried to change the sharp quality to less than 50 but did not change a thing. thank you bro please look into it.

**Comment by HoraceShmorace** [comment]
Can you drop a link to the problematic image? All of my tests seem to result in a much smaller and more optimized image than the original.

**Comment by 7haveeen** [comment]
Hie thanks i solved the issue by removing lossless and set quality to 95.

**Comment by HoraceShmorace** [comment]
Ok, cool. I'll make this the default and more easily configurable in a future release.

**Comment by HoraceShmorace** [comment]
Reopening so that this change can be tracked.

**Comment by 7haveeen** [comment]
Thank you for the update, let me check this out and update you but as for image quality it was for the best to pass the ?q parameter after height.
