### ISSUE TITLE
Is it safe to delete all resized version of images?

### ISSUE THREAD

**Issue by JohnCido** [HoraceShmorace/Image-Flex#24]
We have a bucket of images that has reached the size of 4+TB, and we are seeking to reduce the size of it. Since this project stores resized images within subfolders of a bucket, is it safe to just delete all resized images using a S3 lifecycle rule like `*/` ?

**Comment by HoraceShmorace** [comment]
It's safe to delete any file that is not directly referenced from anywhere on the internet.

**Comment by HoraceShmorace** [comment]
However, note that:

1. If you delete all resized images, they'll still be cached in CloudFront.
2. If you invalidate the paths in CloudFront, then the next time any of them are referenced the system will need to generate them again.
3. If you delete the originals, obviously new sizes won't be able to be generated.
