### ISSUE TITLE
[Question] Why there is need to save processed images to another s3 instead of keeping it at CF cache?

### ISSUE THREAD

**Issue by diimpp** [HoraceShmorace/Image-Flex#4]
Hi,

I'm curios why did you decide to save processed/optimized images to another s3 instead of keeping it at CloudFront cache?
What if I want to invalidate cache of the image, because content of some specific image changed without changing name/path?
Or if I deployed new version of the my AcmeImageFlex with different optimization rules and want to invalidate all webp images in the project.

So what would be benefit of using separate s3 to store processed images? At CF level I can create invalidation at least by file path.

On separate note, great solution, I've learned that much from it and in the process of integrating in our company's production. :)

**Comment by 7haveeen** [comment]
Goos question there. so whats you proposed solution.

**Comment by diimpp** [comment]
I don't have a proposal as I'm yet learning how it should be done properly, but I've outlined in the initial question: Processed images can be stored in cloudfront cache.

For example `cdn.domain.url/images/image.png?t=webp&w=300` will result in processed and cached instance on this image tied to the querystring, which will be served directly from cloudfront and there is no need to keep the copy at s3 and serve image via another lambda call.

What are pros/cons of such approach? I've a feeling, that I'm missing something important here.

**Comment by loginov-rocks** [comment]
Hey guys, as I'm solving a similar problem, decided to comment: store in S3 to save resources on image generation, or use aggressive cache policy not to make origin request at all – both save resources, but in the second option, you should have CloudFront well configured :)

Another solution to cache invalidation is to check the last modified timestamp of the original and requested image in OriginResponse lambda to regenerate image, for that you would need to understand the path to the original image.

**Comment by diimpp** [comment]
@loginov-rocks I've learned since then, that aws doesn't guarantee cache availability and will remove cache on it's own, when it's not in use for long time. (According to their docs) So setting TTL in years won't help, if it's not requested now and then. That's my main take-away why S3 should be used to store processed images, though self-invalidated cache might not be an issue for other use cases.

**Comment by HoraceShmorace** [comment]
> So what would be benefit of using separate s3 to store processed images? At CF level I can create invalidation at least by file path.
I've argued your exact point before. 

The short answer is that a CF distro needs an origin (at which real objects should be stored). More importantly, you have to remember that we're using the `origin-response` event. You can't attach a Lambda@Edge to the `origin-response` event if you have no origin. You can put in a fake origin (like a fake domain), but that's hacky.

**Comment by HoraceShmorace** [comment]
Unless you have more to comment, I'll close this issue.
